### ISSUE TITLE
Apply github labels and workflow github actions

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/buildevents-orb#35]
We apply generic label and workflow github actions to help maintain Honeycomb projects. We should apply them here too.

**Comment by bdarfler** [comment]
@MikeGoldsmith aren't they here already? 

https://github.com/honeycombio/buildevents-orb/labels

https://github.com/honeycombio/buildevents-orb/tree/main/.github/workflows

**Comment by MikeGoldsmith** [comment]
Yep, closing 👍🏻
