### ISSUE TITLE
Add public documentation for buildevents-orb

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/buildevents-orb#43]
**Is your feature request related to a problem? Please describe.**

Currently, in the main docs site, there is no mention of the orb and only a single link out to buildevents. This makes discovery hard.

**Describe the solution you'd like**

Document the orb in the main docs site.

**Describe alternatives you've considered**

**Additional context**

**Comment by brookesargent** [comment]
We have better [public docs](https://docs.honeycomb.io/integrations/ci-cd/buildevents/) for buildevents and it's various CI/CD platform integrations now!
